#!/usr/bin/env python3
"""Apply keyboard layout and Compose-key settings to the running X server.

Ports temp/setlayout.sh and temp/setcompose.sh into a single dump -> patch ->
load round trip. Those scripts each did their own pass, and the Compose one
worked by rewriting the expanded 'key <RALT>' line that the *previous* pass's
dump happened to contain. That can't be merged as-is: replacing the symbols
block with an include deletes every expanded key line, so there is no <RALT>
left to rewrite. Instead the Compose mapping is emitted as an override inside
the new block, right after the include - one round trip, and the resulting
keymap is a pure function of (layout, variant, compose) rather than of
whatever the last apply left behind.

Setting is not persisted by X itself - it has to be re-applied after every
reboot. Callers are responsible for persisting the choice (see
config.save_keyboard_settings) and re-applying it at daemon startup.
"""

import json
import logging
import os
import re
import subprocess

from config import config

log = logging.getLogger(__name__)

__all__ = ['available_layouts', 'is_valid_layout', 'apply_layout']

_CUR_FILE = '/tmp/hid_passthrough_current.xkb'
_NEW_FILE = '/tmp/hid_passthrough_patched.xkb'

_layouts_cache = None


def _display() -> str:
    return os.environ.get('DISPLAY', ':0')


def available_layouts() -> dict:
    """Load the layout/variant name database generated by scripts/gen_layouts_json.py."""
    global _layouts_cache
    if _layouts_cache is None:
        path = os.path.join(config.base_path, 'illusion', 'BTManager', 'layouts.json')
        with open(path, 'r', encoding='utf-8') as f:
            _layouts_cache = json.load(f)
    return _layouts_cache


def is_valid_layout(layout: str, variant: str) -> bool:
    entry = available_layouts().get(layout)
    return entry is not None and variant in entry.get('variants', {})


_SYMBOLS_START_RE = re.compile(r'^xkb_symbols(\s+"(?P<name>[^"]*)")?\s*\{')

# Compose (Multi_key) on Right Alt, as an override after the include.
_COMPOSE_LINE = '  key <RALT> {[Multi_key]};\n'


def _original_symbols_spec(lines: list) -> str:
    """Name of the first xkb_symbols block, i.e. the include spec X built it from.

    A keymap dumped by xkbcomp names its symbols section after the spec the
    rules resolved to, e.g. 'pc+fr+inet(evdev)+terminate(ctrl_alt_bksp)'.
    Returns '' if the block is unnamed or absent.
    """
    for line in lines:
        match = _SYMBOLS_START_RE.match(line)
        if match:
            return match.group('name') or ''
    return ''


def _build_include_target(original_spec: str, layout: str, variant: str) -> str:
    """Splice the chosen layout into the spec X is already using.

    The framework's spec carries more than a layout: 'inet(evdev)' alone
    defines ~100 media/consumer keycodes, and dropping it silently loses
    them. So keep every non-layout component (the 'pc' base and the option
    groups) and substitute only the layout part - all layout components are
    dropped and ours takes the first one's place, so a second group the
    framework may have configured doesn't linger and shadow the choice.

    Components are told apart by name: option groups are things like
    'inet(evdev)' or 'terminate(ctrl_alt_bksp)', whose bare name is never a
    layout in the generated database. If nothing in the spec looks like a
    layout it isn't a rules-resolved spec at all (a framework-supplied keymap
    can name its block anything), and reusing it would include a symbols file
    that doesn't exist - fall back to the bare 'pc+layout' of setlayout.sh.
    """
    spec = f"{layout}({variant})" if variant else layout

    known = available_layouts()
    result = []
    spliced = False
    for part in original_spec.split('+'):
        if not part:
            continue
        # Strip the '(variant)' and ':group' suffixes to get the bare name.
        name = part.split('(', 1)[0].split(':', 1)[0]
        if name in known:
            if not spliced:
                result.append(spec)
                spliced = True
            continue
        result.append(part)

    if not spliced:
        return f"pc+{spec}"
    return '+'.join(result)


def _replace_symbols_block(lines: list, include_target: str, compose: bool) -> list:
    """Swap the file's top-level xkb_symbols {...} block for a single include.

    Mirrors setlayout.sh's awk logic: find the first 'xkb_symbols' block
    (named or not), replace it with an include of include_target, and skip
    past the original block's body by brace counting - quoted strings are
    stripped first so braces inside strings/comments don't throw off the
    count. If no such block exists, append one instead.

    With compose set, a <RALT> override follows the include. It has to live
    here rather than in a pass of its own: the include is unexpanded at this
    point, so there is no other 'key <RALT>' line in the file to patch.
    """
    block = ['xkb_symbols {\n', f'  include "{include_target}"\n']
    if compose:
        block.append(_COMPOSE_LINE)
    block.append('};\n')

    result = []
    i = 0
    replaced = False

    while i < len(lines):
        line = lines[i]
        if not replaced and _SYMBOLS_START_RE.match(line):
            result.extend(block)
            replaced = True

            depth = 1
            i += 1
            while i < len(lines) and depth > 0:
                stripped = re.sub(r'"([^"\\]|\\.)*"', '', lines[i])
                depth += stripped.count('{') - stripped.count('}')
                i += 1
            continue

        result.append(line)
        i += 1

    if not replaced:
        result.append('\n')
        result.extend(block)

    return result


def apply_layout(layout: str, variant: str, compose: bool):
    """Dump the current X keymap, patch it, and reload it in one round trip.

    Raises ValueError for an unknown layout/variant, or
    subprocess.CalledProcessError if xkbcomp itself fails (e.g. no X server
    reachable at DISPLAY).
    """
    if not is_valid_layout(layout, variant):
        raise ValueError(f"Unknown layout/variant: {layout}({variant})")

    display = _display()

    subprocess.run(
        ['xkbcomp', '-xkb', display, _CUR_FILE],
        check=True, capture_output=True, text=True,
    )

    with open(_CUR_FILE, 'r', encoding='utf-8', errors='replace') as f:
        lines = f.readlines()

    include_target = _build_include_target(
        _original_symbols_spec(lines), layout, variant)
    lines = _replace_symbols_block(lines, include_target, compose)

    with open(_NEW_FILE, 'w', encoding='utf-8') as f:
        f.writelines(lines)

    subprocess.run(
        ['xkbcomp', '-I/usr/share/X11/xkb', _NEW_FILE, display],
        check=True, capture_output=True, text=True,
    )

    log.info(f"Applied keyboard layout {include_target} (compose={compose})")
